use thiserror::Error;

use solana_program::program_error::ProgramError;

#[derive(Error, Debug, Copy, Clone)]
pub enum ReflectionError {
	/// Invalid instruction
	#[error("Invalid instruction")]
	InvalidInstruction,

	/// The program address provided doesn't match the value generated by the program.
	#[error("Invalid program address generated from bump seed and key")]
	InvalidProgramAddress,
}

impl From<ReflectionError> for ProgramError {
	fn from(e: ReflectionError) -> Self {
		ProgramError::Custom(e as u32)
	}
}
